spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fruitable #jdbc:mariadb://fruitable.cvjiwbuuly4r.ap-northeast-2.rds.amazonaws.com/fruitable
    username: sa
    password:
    driver-class-name: org.h2.Driver #org.mariadb.jdbc.Driver

  # Naver smtp server 사용
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: emailauthentication@naver.com #네이버 아이디
    password: fruitable123! #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

  jpa:
    hibernate:
      ddl-auto: create
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true


    properties:
      hibernate:
        format_sql: true
        #show_sql: true

logging:
  level:
    org.hibernate.sql: debug
#   org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: fruitable-bucket
    credentials:
      access-key: AKIA36W7FXMSOMKY4IGK
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

img:
  location: /Users/hjhwang/Projects/Spring/apptive-17th-fruitable-backend-main/img #상품 이미지 업로드 경로
  uploadPath: file:///Users/hjhwang/Projects/Spring/ #리소스 업로드 경로

#springdoc swagger
springdoc:
  api-docs:
    enabled: true #false 지정 시 외부 노출 X
  swagger-ui:
    enabled: true